# Gestión de Listas con Numpy

Numpyb es una biblioteca de python que permite realizar cálculos científicos. Se puede decir que es una alternativa mas poderosa que las listas de python. Sin embargo las operaciones en arreglos de multiples dimensiones se realizan mucho mas rápido que con las listas normales.

In [1]:
# lo importamos

import numpy as np

In [2]:
# un arreglo de numpy puede ser creado a partir de ua lista

my_list = [1,2,3,4]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [3]:
# dos arreglos de numpy pueden ser concatenados

my_list1 = [1, 2, 3, 4]
my_list2 = [11, 22, 33, 44]
my_list = [my_list1, my_list2]
my_array = np.array(my_list)
my_array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [4]:
# el atributo shape nos devuelve el tamano del arreglo 

print(my_array.shape)

print(f"my_arry tiene {my_array.shape[0]} filas y {my_array.shape[1]} columnas")

(2, 4)
my_arry tiene 2 filas y 4 columnas


In [5]:
# los arreglos tienen un tipo de dato específico

my_array.dtype

dtype('int32')

In [6]:
# crear un arreglo de zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
# o bien crear un arreglo de unos

np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# tambien podemos crear un arreglo controlando sus elementos
# np.arange([start], [stop], [step_size])

np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
# indexar los arreglos de numpy es exactamente igual que las listas de python

arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
arr[8]

8

In [12]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
# y modificar su valor tambien es igual (en este caso podemos modificar los primeros 5 valores)
arr[0:5] = 3
print(arr)

[ 3  3  3  3  3  5  6  7  8  9 10]


In [14]:
sliced_array = arr[0:6]
print(sliced_array)

sliced_array[5] = 11

print(f"sliced_array: {sliced_array}")

print(f"arr: {arr}")

[3 3 3 3 3 5]
sliced_array: [ 3  3  3  3  3 11]
arr: [ 3  3  3  3  3 11  6  7  8  9 10]


In [15]:
# también podemos cambiar la forma de un arreglo

arr = np.arange(50).reshape(10,5)

print(arr)

print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
(10, 5)


In [16]:
# y hasta calcular su traspuesta

arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [17]:
# operaciones con arreglos de numpy

array1 = np.array([10,20,30,40,50])
array2 = np.arange(5)
print(array2)

print("array1 + array2:", array1 + array2)
print("array1 - array2:", array1 - array2)
print("array1 **2:", array1 ** 2)


[0 1 2 3 4]
array1 + array2: [10 21 32 43 54]
array1 - array2: [10 19 28 37 46]
array1 **2: [ 100  400  900 1600 2500]


In [18]:
# ¿y con operadores lógicos?

print("array1 > 25:", array1 > 25)

print("array2 == 4:", array2 == 4)


array1 > 25: [False False  True  True  True]
array2 == 4: [False False False False  True]


# Operaciones mas complejas

In [19]:
A = np.array([[3,2],[0,1]])
B = np.array([[3,1],[2,1]])

In [20]:
print("A + B")
print(A+B)

A + B
[[6 3]
 [2 2]]


In [21]:
print("A * B")
print(A*B)

A * B
[[9 2]
 [0 1]]


In [22]:
print("A @ B")
print(A@B)

A @ B
[[13  5]
 [ 2  1]]


In [23]:
print("A dot B")
print(A.dot(B))

A dot B
[[13  5]
 [ 2  1]]


In [24]:
# Crear una matriz con valores aleatorios

array = np.random.random((2,2))

print(array)

[[0.39061209 0.97286442]
 [0.11785881 0.06773172]]


In [25]:
print(array.sum())

print(array.min())

1.549067034567822
0.06773171598227579
